language: python
cache: pip

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<2.3"
  - DJANGO="django>=3.0,<3.1"

services:
  - redis-server

branches:
  only:
    - master

before_install:
  - pip install -U -r requirements-test.txt
  - npm install -g jshint
  # temporary: remove when openwisp-utils 0.5.0 is released
  - pip install -U https://github.com/openwisp/openwisp-utils/tarball/master#egg=openwisp_utils[qa]

install:
  - pip install $DJANGO
  - pip install -e .[rest]

script:
  - ./run-qa-checks
  - coverage run --source=openwisp_users runtests.py

after_success:
  coveralls
